# Generated by Django 3.2 on 2023-08-22 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
