# Generated by Django 3.2 on 2023-08-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20230822_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
