# Generated by Django 3.2 on 2023-08-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_customer_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charged_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charged_date', models.DateField(auto_now_add=True, null=True)),
                ('charged_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.customer')),
            ],
        ),
    ]
