# Generated by Django 3.2 on 2023-08-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_auto_20230824_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
