# Generated by Django 3.2 on 2023-08-28 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0006_withdrawalrequest_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_withdrawal_requests', related_query_name='approved_withdrawal_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='approved_date',
            field=models.DateField(),
        ),
    ]
